#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "datasets>=3.0.0",
# ]
# ///
"""Download sample transcripts from Omi-Health medical-dialogue-to-soap-summary dataset.

Downloads dialogues with pre-formatted SOAP notes and creates:
- Labeled seed data (database/seed_corpus.py) for pre-populating the DB
- Unlabeled transcripts (sample-transcripts/) for testing extraction

Usage:
    ./scripts/download-transcripts.py [--labeled N] [--unlabeled N]

Source: https://huggingface.co/datasets/omi-health/medical-dialogue-to-soap-summary
"""

import argparse
import random
import re
from pathlib import Path

from datasets import load_dataset

FIRST_NAMES = [
    "Emma", "Liam", "Olivia", "Noah", "Ava", "William", "Sophia", "James",
    "Isabella", "Benjamin", "Charlotte", "Elijah", "Amelia", "Lucas", "Mia",
    "Mason", "Harper", "Ethan", "Evelyn", "Alexander",
]
LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
    "Davis", "Rodriguez", "Martinez", "Anderson", "Taylor", "Thomas", "Moore",
    "Jackson", "Martin", "Lee", "Thompson", "White", "Harris",
]


def generate_patient_info(index: int) -> dict:
    """Generate consistent patient info for a given index."""
    random.seed(index + 1000)
    name = f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}"
    birth_year = random.randint(1950, 2000)
    birth_month = random.randint(1, 12)
    birth_day = random.randint(1, 28)
    visit_day = random.randint(1, 28)
    visit_hour = random.randint(8, 17)
    visit_minute = random.choice([0, 15, 30, 45])
    return {
        "name": name,
        "dob": f"{birth_year}-{birth_month:02d}-{birth_day:02d}",
        "visit_date": f"2026-01-{visit_day:02d}T{visit_hour:02d}:{visit_minute:02d}:00",
    }


def parse_soap_note(soap: str) -> dict:
    """Parse SOAP note into individual sections.

    The Omi-Health dataset uses this format:
    S: subjective text...
    O: objective text...
    A: assessment text...
    P: plan text...
    """
    sections = {"subjective": "", "objective": "", "assessment": "", "plan": ""}

    # Match each section - handles multiline content until next section or end
    patterns = [
        (r"S:\s*(.*?)(?=\n[OAP]:|$)", "subjective"),
        (r"O:\s*(.*?)(?=\n[AP]:|$)", "objective"),
        (r"A:\s*(.*?)(?=\nP:|$)", "assessment"),
        (r"P:\s*(.*?)$", "plan"),
    ]

    for pattern, key in patterns:
        match = re.search(pattern, soap, re.DOTALL | re.IGNORECASE)
        if match:
            sections[key] = match.group(1).strip()

    return sections


def extract_active_problems(assessment: str) -> list[str]:
    """Extract likely active problems from the assessment section."""
    problems = []

    # Look for common diagnosis patterns
    diagnosis_patterns = [
        r"primary diagnosis[:\s]+([^.]+)",
        r"diagnosis[:\s]+([^.]+)",
        r"diagnosed with\s+([^.]+)",
        r"assessment[:\s]+([^.]+)",
    ]

    for pattern in diagnosis_patterns:
        matches = re.findall(pattern, assessment, re.IGNORECASE)
        for match in matches:
            # Clean up and add if not too long
            problem = match.strip().rstrip(",;")
            if len(problem) < 100 and problem:
                problems.append(problem)
                break  # Only take first match per pattern

    # If no patterns matched, take first sentence as the problem
    if not problems and assessment:
        first_sentence = assessment.split(".")[0].strip()
        if len(first_sentence) < 100:
            problems.append(first_sentence)

    return problems[:3]  # Limit to 3 active problems


def format_transcript(dialogue: str, info: dict) -> str:
    """Format a dialogue as a transcript file with patient header."""
    header = f"""Patient: {info['name']}
Date of Birth: {info['dob']}
Visit Date: {info['visit_date']}

"""
    return header + dialogue


def sanitize_filename(text: str, max_len: int = 30) -> str:
    """Create a safe filename from text."""
    safe = "".join(c if c.isalnum() or c in " -_" else "" for c in text.lower())
    safe = "-".join(safe.split())
    return safe[:max_len] if safe else "transcript"


def escape_string(s: str) -> str:
    """Escape a string for Python source code."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_seed_file(labeled_data: list[dict], output_path: Path) -> None:
    """Write labeled data as a Python seed file."""
    content = '''"""Corpus-sourced seed data from Omi-Health medical-dialogue-to-soap-summary.

Auto-generated by scripts/download-transcripts.py
Source: https://huggingface.co/datasets/omi-health/medical-dialogue-to-soap-summary
"""

CORPUS_PATIENTS = [
'''
    for item in labeled_data:
        problems_json = str(item["active_problems"]).replace("'", '"')
        content += f'    {{"name": "{item["name"]}", "date_of_birth": "{item["dob"]}", "active_problems": \'{problems_json}\'}},\n'

    content += ''']

CORPUS_VISITS = [
'''
    for i, item in enumerate(labeled_data):
        transcript = escape_string(item["transcript"][:2000])
        subjective = escape_string(item["subjective"][:1000])
        objective = escape_string(item["objective"][:1000])
        assessment = escape_string(item["assessment"][:500])
        plan = escape_string(item["plan"][:1000])

        content += f'''    {{
        "patient_id": {i + 1},
        "visit_date": "{item["visit_date"]}",
        "transcript": "{transcript}",
        "subjective": "{subjective}",
        "objective": "{objective}",
        "assessment": "{assessment}",
        "plan": "{plan}",
    }},
'''

    content += ''']
'''
    output_path.write_text(content)
    print(f"Wrote {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Download sample clinical transcripts from Omi-Health")
    parser.add_argument("--labeled", "-l", type=int, default=7, help="Number of labeled records for DB seeding")
    parser.add_argument("--unlabeled", "-u", type=int, default=5, help="Number of unlabeled transcripts for testing")
    parser.add_argument("--output-dir", "-o", type=Path, default=Path("sample-transcripts"), help="Output directory for unlabeled")
    parser.add_argument("--clean", action="store_true", help="Remove existing transcripts before downloading")
    args = parser.parse_args()

    output_dir = args.output_dir
    output_dir.mkdir(exist_ok=True)

    if args.clean:
        for f in output_dir.glob("*.txt"):
            f.unlink()
        print(f"Cleaned {output_dir}/")

    # Load Omi-Health dataset from Hugging Face
    print("Loading Omi-Health dataset from Hugging Face...")
    dataset = load_dataset("omi-health/medical-dialogue-to-soap-summary", split="train")
    print(f"Loaded {len(dataset)} dialogues")

    # Select random samples
    total_needed = args.labeled + args.unlabeled
    random.seed(42)
    indices = random.sample(range(len(dataset)), min(total_needed, len(dataset)))

    labeled_indices = indices[:args.labeled]
    unlabeled_indices = indices[args.labeled:args.labeled + args.unlabeled]

    # Process labeled samples for DB seeding
    labeled_data = []
    for i, idx in enumerate(labeled_indices):
        row = dataset[idx]
        info = generate_patient_info(i)
        soap_sections = parse_soap_note(row["soap"])
        active_problems = extract_active_problems(soap_sections["assessment"])

        labeled_data.append({
            "name": info["name"],
            "dob": info["dob"],
            "visit_date": info["visit_date"],
            "active_problems": active_problems,
            "transcript": row["dialogue"],
            **soap_sections,
        })

    if labeled_data:
        seed_path = Path("database/seed_corpus.py")
        write_seed_file(labeled_data, seed_path)

    # Write unlabeled transcript files
    for i, idx in enumerate(unlabeled_indices):
        row = dataset[idx]
        index = args.labeled + i
        info = generate_patient_info(index)
        transcript = format_transcript(row["dialogue"], info)

        filename = f"visit-{i + 1:03d}.txt"
        filepath = output_dir / filename
        filepath.write_text(transcript)
        print(f"Wrote {filepath}")

    print(f"\nCreated {len(labeled_data)} labeled records in database/seed_corpus.py")
    print(f"Created {len(unlabeled_indices)} unlabeled transcripts in {output_dir}/")
    return 0


if __name__ == "__main__":
    exit(main())
