-- Plugins Directory
--
-- All plugin configurations organized in one place.
-- Each plugin is in its own file for better organization and maintainability.
--
-- Current plugins:
--   - autopairs.lua        : Auto-insert matching pairs
--   - colorscheme.lua      : Tokyonight colorscheme
--   - gitsigns.lua         : Git integration
--   - guess-indent.lua     : Auto indent detection
--   - lazydev.lua          : Lua development tools
--   - lsp-autocomplete.lua : Completion (blink.cmp)
--   - lsp-autoformat.lua   : Auto formatting
--   - lsp-config.lua       : LSP servers
--   - mini.lua             : Mini.nvim collection (textobjects, surround, statusline)
--   - neo-tree.lua         : File explorer
--   - telescope.lua        : Fuzzy finder
--   - todo-comments.lua    : TODO/FIXME/NOTE highlighting
--   - treesitter.lua       : Treesitter syntax highlighting
--   - which-key.lua        : Keybinding helper
--
-- To add a new plugin:
--   1. Create a new .lua file in this directory
--   2. Return a plugin spec table following lazy.nvim format
--   3. It will be automatically loaded by { import = 'plugins' } in init.lua
--
-- Example plugin spec:
--   return {
--     'author/plugin-name',
--     config = function()
--       require('plugin-name').setup({
--         -- your configuration here
--       })
--     end,
--   }
--
-- For more information on plugin specs, see:
--   :help lazy.nvim-plugin-spec
--
-- You can also add plugins directly to this file if you prefer:
return {
  -- Add simple plugin specs here without creating separate files
  -- Example:
  -- { 'author/simple-plugin', opts = {} },
}
